USE [master]
GO

/****** Object:  Database [GTDA]    Script Date: 29/5/2023 09:50:15 ******/
CREATE DATABASE [GTDA]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'GTDA', FILENAME = N'D:\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\GTDA.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'GTDA_log', FILENAME = N'D:\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\GTDA_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [GTDA].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [GTDA] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [GTDA] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [GTDA] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [GTDA] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [GTDA] SET ARITHABORT OFF 
GO

ALTER DATABASE [GTDA] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [GTDA] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [GTDA] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [GTDA] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [GTDA] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [GTDA] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [GTDA] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [GTDA] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [GTDA] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [GTDA] SET  ENABLE_BROKER 
GO

ALTER DATABASE [GTDA] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [GTDA] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [GTDA] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [GTDA] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [GTDA] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [GTDA] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [GTDA] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [GTDA] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [GTDA] SET  MULTI_USER 
GO

ALTER DATABASE [GTDA] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [GTDA] SET DB_CHAINING OFF 
GO

ALTER DATABASE [GTDA] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [GTDA] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [GTDA] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [GTDA] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [GTDA] SET QUERY_STORE = OFF
GO

ALTER DATABASE [GTDA] SET  READ_WRITE 
GO


